### ISSUE TITLE
[Crash] Running the patch immediately crashes my game on startup (v2.0)

### ISSUE THREAD

**Issue by NeverEndingCycle** [shiversoftdev/t7patch#29]
I've tried re-installing the game. I've tried starting the patch after the game has started and that crashes it instantly. Using fresh settings also changed nothing. The error log created this exact error every time I launch my game: 

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: 32
   at System.ProcessEx.GetBytes(PointerEx res, PointerEx map)
   at System.ProcessEx.GetValue[T](PointerEx reference)
   at System.ProcessEx.RateManager(PointerEx last, PointerEx cust)
   at System.ProcessEx.<__CallAsync>d__61`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.ProcessEx.Call(PointerEx spec, Object[] args)
   at t7dwidm_protect.MainForm.QueryWatcher()
---> (Inner Exception #0) System.InvalidOperationException: 32
   at System.ProcessEx.GetBytes(PointerEx res, PointerEx map)
   at System.ProcessEx.GetValue[T](PointerEx reference)
   at System.ProcessEx.RateManager(PointerEx last, PointerEx cust)
   at System.ProcessEx.<__CallAsync>d__61`1.MoveNext()<---
```

**Comment by NeverEndingCycle** [comment]
Alright, not antivirus. However, I have discovered the issue and will a separate ticket for it.

**Comment by NeverEndingCycle** [comment]
#30
