### ISSUE TITLE
Not working on proton

### ISSUE THREAD

**Issue by 2Epik4u** [shiversoftdev/t7patch#51]
Trying to run the patch crashes instantly with this crash log (tried proton experimental, latest wine and proton 7.02 with same issue)

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializerOptions' threw an exception. ---> System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Text.Json.JsonSerializerOptions.GetDefaultSimpleConverters()
   at System.Text.Json.JsonSerializerOptions..cctor()
   --- End of inner exception stack trace ---
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at t7dwidm_protect.MainForm.ValidateWatcher()
   at t7dwidm_protect.MainForm..ctor()
   at Refract.Resolver.RoleDatabaseResolver.CancelWatcher()
   at <PrivateImplementationDetails>{66271CF5-3CFD-49FC-80A3-6B44FD29D673}.Main()
Unhandled exception: 0xe0434352 in 64-bit code (0x0000007b00cd77).

```

**Comment by shiversoftdev** [comment]
Yeah I know it doesnt work on proton.
